GET http://fso03-phonebook.fly.dev/api/persons

###
GET http://fso03-phonebook.fly.dev/api/persons/1

###
DELETE http://fso03-phonebook.fly.dev/api/persons/1

###
DELETE http://fso03-phonebook.fly.dev/api/persons/5

###
POST http://fso03-phonebook.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Tim O'Thea",
  "number": "123-4-5-6789-10-11-12"
}